name: Translation Stats

on:
  push:
    paths:
      - 'translations/**.json'
  pull_request:
    paths:
      - 'translations/**.json'

permissions:
  contents: write

jobs:
  validate_and_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Diagnostics
        run: python .github/scripts/compute_stats.py

      - name: Commit Diagnostics Report
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/reports/translation_report.json
          git commit -m "docs: update translation report [skip ci (Github Actions) ]" || exit 0
          git push